### ISSUE TITLE
3. DB Setup

### ISSUE THREAD

**Issue by rentala** [SJSU272Lab/Fall16-Team21#8]
Includes mock data set up

**Comment by nilamdeka23** [comment]
MongoDB is setup on the cloud(mLab) with mock data.
At present 10 datasets to begin work with.

To connect using the mongo shell:
mongo ds155727.mlab.com:55727/agentimongo -u <dbuser> -p <dbpassword>

To connect using a driver via the standard MongoDB URI :
mongodb://<dbuser>:<dbpassword>@ds155727.mlab.com:55727/agentimongo

dbuser and dbpassword I will share on the group for privacy reasons.
